In [9]:
import pandas as pd 
import numpy as np 
df = pd.read_csv('animal_data_dirty1.csv',sep=';')
df.head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony

In [4]:
df.shape

(1011, 11)

In [5]:
df.describe()

         Weight kg  Body Length cm  Animal code    Latitude   Longitude
count   984.000000      984.000000          0.0  913.000000  913.000000
mean     39.745503       39.107724          NaN   49.393369   18.203280
std     156.290076       58.628601          NaN    7.168900    3.899601
min      -0.252000      -19.000000          NaN  -78.582973   11.074008
25%       0.293000       19.000000          NaN   48.186913   14.384559
50%       0.331500       21.000000          NaN   49.560723   18.944015
75%       0.800000       23.000000          NaN   52.212433   21.033243
max    1100.000000      350.000000          NaN   52.853843   34.896734

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       991 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  1011 non-null   object
 10  Data compiled by  1011 non-null   object
dtypes: float64(5), object(6)
memory usage: 87.0+ KB

In [7]:
df.isnull().sum()

Animal type           20
Country               12
Weight kg             27
Body Length cm        27
Gender                19
Animal code         1011
Latitude              98
Longitude             98
Animal name          959
Observation date       0
Data compiled by       0
dtype: int64

In [8]:
df.columns

Index(['Animal type', 'Country', 'Weight kg', 'Body Length cm', 'Gender',
       'Animal code', 'Latitude', 'Longitude', 'Animal name',
       'Observation date', 'Data compiled by'],
      dtype='object')

In [14]:
for columna in df.select_dtypes(include='object').columns:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts())

--- Animal type ---
Animal type
red squirrel       543
hedgehog           274
lynx                61
European bison      49
red squirrell       22
red squirel         14
lynx?               10
European bison™      6
European bisson      4
European buster      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

--- Country ---
Country
Poland            291
Germany           176
Slovakia          151
Hungary           146
Czech Republic    103
Austria            74
PL                 15
HU                 11
Hungry             10
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

--- Gender ---
Gender
male              499
female            488
not determined      5
Name: count, dtype: int64

--- Animal name ---
Animal name
Bob Bobson    18
Basia         10
Lola           9
Lolek          4
Zuzia          4
Sissi          2
Puchatek       2
Szefu          1
Klucha         1
Bibi           1
Name: count, dtype: int64

--- Observation date ---
Observation date
01.03.2024    61
02.03.2024    47
06.04.2024    45
04.03.2024    43
02.04.2024    41
              ..
03.05.2024     1
26.04.2024     1
03.02.2024     1
23.04.2024     1
8 May 2024     1
Name: count, Length: 114, dtype: int64

--- Data compiled by ---
Data compiled by
Anne Anthony     473
Bob Bobson       259
John Johnson     249
James Johnson     30
Name: count, dtype: int64

Los problemas encontrados:

Al revisar los datos encontré varios errores. En los nombres de los animales hay algunos errores de escritura, espacios y símbolos. En los países hay diferencias porque algunos aparecen con el nombre completo y otros con abreviaciones. También hay varios datos vacíos y algunos valores que no parecen correctos, como pesos y longitudes negativas.

In [43]:
df = df.drop(columns='Animal code')

In [44]:
df.columns

Index(['Animal type', 'Country', 'Weight kg', 'Body Length cm', 'Gender',
       'Latitude', 'Longitude', 'Animal name', 'Observation date',
       'Data compiled by'],
      dtype='object')

In [45]:
df['Animal name'].value_counts()

Animal name
Bob Bobson    18
Basia          5
Lola           5
Lolek          2
Zuzia          2
Sissi          2
Szefu          1
Klucha         1
Bibi           1
Puchatek       1
Name: count, dtype: int64

In [46]:
df['Weight kg'].isnull().sum()

np.int64(0)

In [7]:
df[df['Weight kg'] < 0]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
457,red squirrel,Hungary,-0.251,20.0,female,47.508618,18.944915,NaN,26.03.2024,Anne Anthony
461,red squirrel,Hungary,-0.251,20.0,female,47.508618,18.944915,NaN,26.03.2024,Anne Anthony
503,red squirrel,Hungary,-0.250,19.0,female,47.509538,18.945968,NaN,31.03.2024,Anne Anthony
507,red squirrel,Hungary,-0.250,19.0,female,47.509538,18.945968,NaN,31.03.2024,Anne Anthony
663,red squirrel,Slovakia,-0.252,21.0,male,49.057599,22.422203,NaN,08.04.2024,John Johnson

In [10]:
df.loc[df['Weight kg'] < 0, 'Weight kg'] = np.nan

In [18]:
df['Animal type'] = df['Animal type'].str.strip()

In [25]:
df['Animal type'] = df['Animal type'].replace({
    'European bison™': 'European bison',
    'European bisson': 'European bison',
    'European buster': 'European bison',
    'ledgehog': 'hedgehog',
    'wedgehog': 'hedgehog',
    'red squirrel!': 'red squirrel',
    'lynx?': 'lynx'
})

In [26]:
df['Animal type'].value_counts()

Animal type
red squirrel      565
hedgehog          274
lynx               71
European bison     63
red squirel        14
ledgehod            3
wedgehod            1
Name: count, dtype: int64

In [27]:
df['Weight kg'] = df['Weight kg'].fillna(
    df.groupby('Animal type')['Weight kg'].transform('median')
)

In [28]:
df['Body Length cm'] = df['Body Length cm'].fillna(
    df.groupby('Animal type')['Body Length cm'].transform('median')
)

In [31]:
df['Weight kg'] = df['Weight kg'].fillna(df['Weight kg'].median())

df['Body Length cm'] = df['Body Length cm'].fillna(df['Body Length cm'].median())

In [32]:
df['Weight kg'].isnull().sum()

np.int64(0)

In [33]:
df['Body Length cm'].isnull().sum()

np.int64(0)

In [34]:
df.duplicated().sum()

np.int64(167)

In [35]:
df = df.drop_duplicates()

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df['Observation date'] = pd.to_datetime(
    df['Observation date'],
    format='%d.%m.%Y',
    errors='coerce'
)

In [38]:
df['Observation date'].dtype

dtype('<M8[ns]')

In [39]:
df['Country'].value_counts()

Country
Poland            182
Germany           173
Slovakia          151
Hungary           103
Czech Republic    103
Austria            74
PL                 10
HU                  8
Hungry              7
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

In [40]:
df['Country'] = df['Country'].str.strip()

df['Country'] = df['Country'].replace({
    'PL': 'Poland',
    'HU': 'Hungary',
    'CZ': 'Czech Republic',
    'DE': 'Germany',
    'Hungry': 'Hungary',
    'Czech': 'Czech Republic',
    'CC': np.nan
})

In [41]:
df['Country'].value_counts()

Country
Poland            192
Germany           178
Slovakia          151
Hungary           118
Czech Republic    112
Austria            74
Australia           4
Name: count, dtype: int64

In [48]:
print("Dimensiones:", df.shape)

print("\nValores faltantes:")
print(df.isnull().sum())

print("\nDuplicados:", df.duplicated().sum())

print("\nTipos de datos:")
print(df.dtypes)

Dimensiones: (844, 10)

Valores faltantes:
Animal type          19
Country              15
Weight kg             0
Body Length cm        0
Gender               15
Latitude             92
Longitude            92
Animal name         806
Observation date     35
Data compiled by      0
dtype: int64

Duplicados: 2

Tipos de datos:
Animal type                 object
Country                     object
Weight kg                  float64
Body Length cm             float64
Gender                      object
Latitude                   float64
Longitude                  float64
Animal name                 object
Observation date    datetime64[ns]
Data compiled by            object
dtype: object

In [49]:
df = df.drop_duplicates()

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df.shape

(842, 10)

Resultado: 
En esta parte revisé y limpié los datos del archivo, encontré algunos valores faltantes, datos repetidos y errores en los nombres de los animales y países. También encontré algunos pesos negativos, por lo que los tomé como datos faltantes y los completé usando la mediana, hice algo similar con la longitud de los animales. Además, eliminé los registros duplicados y cambié la columna de fecha al formato correcto, finalmente revisé nuevamente los datos para comprobar que la limpieza se hubiera realizado correctamente.